<?php

/*================================================================/

 Techni-Contact V2 - MD2I SAS
 http://www.techni-contact.com

 Auteur : Hook Network SARL - http://www.hook-network.com
 Date de cr�ation : 20 d�cembre 2004

 Mises � jour :

       31 mai 2005 : = nouveau gestionnaire de rangs
                     + gestion session s�curis�e avec contr�le adresse ip

 Fichier : /includes/classV2/ManagerUser.php4
 Description : Classe utilisateur manager

/=================================================================*/

/*$oldid = session_id();
session_regenerate_id();
unlink('/tmp/sess_' . $oldid);*/

class Email
{
	/* Handle connexion */
	var $handle = NULL;
	
	var $id = 0;					// Email ID in DB
  var $sent_time = 0;
	var $email = "";				// Recipient Email
	var $subject = "";				// Subject of the Email
	var $content = "";				// Content of the original mail
	var $content_type = 0;			// Type of content, (can be used for a new send in case of a change of the mail body)
	var $headers = "";				// Headers of the mail. Kept entirely for future compatibilities purpose
	
	var $lastErrorMessage = '';		// Last Error generated by the object
	
	/*	status
		0 = not determined
		1 = doesn't exist in DB
		2 = exist in DB */
	var $status = 0;
	
	var $stats = true;				// If the object must update some stats
	
	/* Constructor */
	function Email(& $handle, $id = NULL, $stats = true)
	{
		$this->handle = & $handle;
		$this->stats = $stats;
		if ($id != NULL) $this->id = $id;
	}
	
	/* Generate a random ID */
	function GenerateID()
	{
		do
		{
			$id = mt_rand(1, 999999999);
			$result = & $this->handle->query("select id from emails_historic where id = " . $id, __FILE__, __LINE__);
		}
		while ($this->handle->numrows($result, __FILE__, __LINE__) == 1);
		
		$this->status = 1;
		$this->id = $id;
	}
	
	function Load()
	{
		$this->lastErrorMessage = '';
		
		$query = "select sent_time, email, subject, content, content_type, headers from emails_historic where id = " . $this->id;
		if ($res = & $this->handle->query($query, __FILE__, __LINE__))
		{
			if ($this->handle->numrows($res, __FILE__, __LINE__) > 0)
			{
				$rec = & $this->handle->fetchAssoc($res);
				foreach($rec as $name => $value) $this->$name = $value;
				
				$this->status = 2;
				return true;
			}
			else
			{
				$this->status = 1;
				$this->lastErrorMessage = "The Given Email ID does not exist in the Database.";
				return false;
			}
		}
		else
		{
			$this->lastErrorMessage = "Mysql Fatal Error";
			return false;
		}
	}
	
	function Save()
	{
		// ID set but no status check done
		if ($this->id == 0)
		{
			$this->GenerateID();
		}
		elseif ($this->status == 0)
		{
			$query = "select id from emails_historic where id = " . $this->id;
			if ($res = & $this->handle->query($query, __FILE__, __LINE__))
			{
				if ($this->handle->numrows($res, __FILE__, __LINE__) == 1) $this->status = 2;
				else $this->status = 1;
			}
		}
		
		$query = "";
		
		if ($this->status == 1)
		{
			$query = "insert into emails_historic (";			$query2 .= "values (";
			$query .= "id, ";									$query2 .= $this->id . ", ";
			$query .= "sent_time, ";							$query2 .= "'" . $this->handle->escape($this->sent_time) . "', ";
			$query .= "email, ";								$query2 .= "'" . $this->handle->escape($this->email) . "', ";
			$query .= "subject, ";								$query2 .= "'" . $this->handle->escape($this->subject) . "', ";
			$query .= "content, ";								$query2 .= "'" . $this->handle->escape($this->content) . "', ";
			$query .= "content_type, ";							$query2 .= "'" . $this->content_type . "', ";
			$query .= "headers) ";								$query2 .= "'" . $this->handle->escape($this->headers) . "')";
			$query .= $query2;
		}
		elseif ($this->status == 2)
		{
			$query .= "update emails_historic set " .
			"sent_time = " .									"'" . $this->handle->escape($this->sent_time) . "', " .
			"email = " .										"'" . $this->handle->escape($this->email) . "', " .
			"subject = " .										"'" . $this->handle->escape($this->subject) . "', " .
			"content = " .										"'" . $this->handle->escape($this->content) . "', " .
			"content_type = " .									"'" . $this->content_type . "', " .
			"headers = " .										"'" . $this->handle->escape($this->headers) . "' " .
			"where id = " . $this->id;
		}
		
    $charset = $this->handle->get_charset();
    if ($charset != 'latin1')
      $this->handle->set_charset('latin1');
    
    $this->handle->query($query, __FILE__, __LINE__);
    
    if ($charset != 'latin1')
      $this->handle->set_charset($charset);
		
		$this->status = 2;
	}
	
	function Build($subject = "[www.Techni-Contact.com]", $title, $content_type, $headers = "", $data, $header_type = "user")
	{
    mb_convert_variables("UTF-8", "UTF-8,ISO-8859-1", $subject, $data);
		$this->headers = $headers .
			"MIME-Version: 1.0\n" .
			"Content-type: text/html; charset=utf-8\n";
		$this->subject = $subject;
		$this->content_type = $content_type;
		
		$constant = get_defined_constants();
		
		if ($header_type === true || $header_type == "old") {
			include(MISC_INC."emails_content/header_old.php");
			include(MISC_INC."emails_content/".$content_type.".php");
			include(MISC_INC."emails_content/footer_old.php");
		}
		else {
			$header_type = strtolower($header_type);
			switch ($header_type) {
				case "user":
				case "partner":
        case "prospect":
				case "tc":
					$this->content .= file_get_contents(MISC_INC."emails_content/header_".$header_type.".dat");
					$this->content .= str_replace(array_keys($data), array_values($data), file_get_contents(MISC_INC."emails_content/".$content_type.".dat"));
					$this->content .= file_get_contents(MISC_INC."emails_content/footer_".$header_type.".dat");
					break;
				default:
			}
		}
	}
	
	function Send($email) {
    if (!DEBUG && !TEST)
      if (!mail($email, $this->subject, $this->content, $this->headers))
        return false;
		$this->email = $email;
    $this->sent_time = time();
		return true;
	}
	
}
