<?php

/**
 * ActivitySectorSurqualificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivitySectorSurqualificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivitySectorSurqualificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivitySectorSurqualification');
    }
}