<?php

/**
 * ActivitySector
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ActivitySector extends BaseActivitySector
{
  public function setUp() {
    parent::setUp();
    $this->hasMany('ActivitySectorSurqualification as Surqualifications', array(
        'local' => 'id',
        'foreign' => 'activity_sector_id'
      )
    );
  }
}