<?php

/**
 * ActivitySectorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivitySectorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivitySectorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivitySector');
    }
}