<?php

/**
 * Advertisers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Advertisers extends BaseAdvertisers
{
  public function setUp()
  {
    parent::setUp();
    $this->setAttribute(Doctrine_Core::ATTR_AUTO_ACCESSOR_OVERRIDE, true);
    $this->hasMany('Estimate as estimates', array(
        'local' => 'id',
        'foreign' => 'main_sup_id'
      )
    );
    $this->hasMany('Products as products', array(
        'local' => 'id',
        'foreign' => 'idAdvertiser'
      )
    );
    $this->hasOne('Extranetusers as extranet_user', array(
        'local' => 'id',
        'foreign' => 'id'
      )
    );
    $this->hasMany('Contacts as contacts', array(
        'local' => 'id',
        'foreign' => 'idAdvertiser'
      )
    );
    $this->hasOne('Clients as client', array(
        'local' => 'client_id',
        'foreign' => 'id'
      )
    );
  }
  
  public function getContacts($load) {
    return mb_unserialize($this->_get('contacts', $load));
  }
  
  public function setContacts($load, $contacts) {
    return $this->_set('contacts', serialize($contacts), $load);
  }
  
  public function getIsFields($load) {
    return mb_unserialize($this->_get('is_fields', $load));
  }
  
  public function setIsFields($load, $is_fields) {
    return $this->_set('is_fields', serialize($is_fields), $load);
  }
  
  public function preInsert() {
    $this->create_time = $this->timestamp = time();
  }
  
  public function preUpdate() {
    if ($this->isModified())
      $this->timestamp = time();
  }
  
}