<?php

/**
 * AdvertisersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdvertisersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdvertisersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Advertisers');
    }
}