<?php

/**
 * AttributeUnit
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AttributeUnit extends BaseAttributeUnit
{
  public function setUp() {
    parent::setUp();
    $this->hasMany('AttributeUnit as linked_unit', array(
        'local' => 'id',
        'foreign' => 'parent_id'
      )
    );
    $this->hasOne('AttributeUnit as parent_unit', array(
        'local' => 'parent_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Attribute as attribute', array(
        'local' => 'attribute_id',
        'foreign' => 'id'
      )
    );
    $this->hasMany('ProductAttribute as product_attributes', array(
        'local' => 'id',
        'foreign' => 'attribute_unit_id'
      )
    );
    $this->hasMany('Facet as facet', array(
        'local' => 'id',
        'foreign' => 'attribute_unit_id'
      )
    );
    $this->hasMany('FacetLine as facet_line', array(
        'local' => 'id',
        'foreign' => 'attribute_unit_id'
      )
    );
  }

}
