<?php

/**
 * AttributeUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AttributeUnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AttributeUnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AttributeUnit');
    }
}