<?php

/**
 * BoUsersPermissionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BoUsersPermissionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BoUsersPermissionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BoUsersPermissions');
    }
}