<?php

/**
 * BoUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BoUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BoUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BoUsers');
    }
}