<?php

/**
 * BoUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BoUsers extends BaseBoUsers
{
  public function setUp() {
    parent::setUp();
    $this->hasMany('Contacts as leads_processed', array(
        'local' => 'id',
        'foreign' => 'id_user_processed'
      )
    );
    $this->hasMany('Estimate as estimates_created', array(
        'local' => 'id',
        'foreign' => 'created_user_id'
      )
    );
    $this->hasMany('Estimate as estimates_updated', array(
        'local' => 'id',
        'foreign' => 'updated_user_id'
      )
    );
    $this->hasMany('Order as orders_created', array(
        'local' => 'id',
        'foreign' => 'created_user_id'
      )
    );
    $this->hasMany('Order as orders_updated', array(
        'local' => 'id',
        'foreign' => 'updated_user_id'
      )
    );
    $this->hasMany('Order as orders_in_charge', array(
        'local' => 'id',
        'foreign' => 'in_charge_user_id'
      )
    );
    $this->hasMany('Order as orders_oked', array(
        'local' => 'id',
        'foreign' => 'oked_user_id'
      )
    );
    $this->hasMany('Order as orders_validated', array(
        'local' => 'id',
        'foreign' => 'validated_user_id'
      )
    );
    $this->hasMany('Order as orders_partly_cancelled', array(
        'local' => 'id',
        'foreign' => 'partly_cancelled_user_id'
      )
    );
    $this->hasMany('Order as orders_cancelled', array(
        'local' => 'id',
        'foreign' => 'cancelled_user_id'
      )
    );
    $this->hasMany('SupplierOrder as supplier_orders', array(
        'local' => 'id',
        'foreign' => 'sender_id'
      )
    );
    $this->hasMany('Invoice as invoices_created', array(
        'local' => 'id',
        'foreign' => 'created_user_id'
      )
    );
    $this->hasMany('Invoice as invoices_updated', array(
        'local' => 'id',
        'foreign' => 'updated_user_id'
      )
    );
    $this->hasMany('Invoice as invoices_issued', array(
        'local' => 'id',
        'foreign' => 'issued_user_id'
      )
    );
  }
}