<?php

/**
 * ClientsAdressesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientsAdressesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientsAdressesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientsAdresses');
    }
}