<?php

/**
 * ClientsContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientsContactsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientsContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientsContacts');
    }
}