<?php

/**
 * ClientsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clients');
    }
}