<?php

/**
 * ContactsAborted
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContactsAborted extends BaseContactsAborted
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('ProductsFr as productFr', array(
        'local' => 'idProduct',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Families as category', array(
        'local' => 'idFamily',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Advertisers as advertiser', array(
        'local' => 'idAdvertiser',
        'foreign' => 'id'
      )
    );
  }
  
    public function preSave($event) {
    if (empty($this->web_id))
      $this->genId('web_id');
    }
}