<?php

/**
 * ContactsAbortedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactsAbortedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactsAbortedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactsAborted');
    }
}