<?php

/**
 * EstimateLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstimateLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstimateLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstimateLine');
    }
}