<?php

/**
 * EstimateLine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EstimateLine extends BaseEstimateLine
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('Estimate as estimate', array(
        'local' => 'estimate_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Advertisers as supplier', array(
        'local' => 'sup_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Products as product', array(
        'local' => 'pdt_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('ReferencesContent as pdt_ref', array(
        'local' => 'pdt_ref_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Tva as tva', array(
        'local' => 'tva_code',
        'foreign' => 'id'
      )
    );
  }
  
  public function construct() {
    $this->mapValue('total_a_ht', 0);
    $this->mapValue('total_tva', 0);
    $this->mapValue('total_ht_pre', 0);
    $this->mapValue('et_total_ht', 0);
    $this->mapValue('et_total_tva', 0);
  }
  
  public function postHydrate($event) {
    $data = $event->data;
    $data['total_a_ht'] = $data['pau_ht'] * $data['quantity'];
    $data['total_tva'] = $data['total_ttc'] - $data['total_ht'];
    $data['total_ht_pre'] = $data['pu_ht'] * $data['quantity']; // total ht without discount/promotion
    $data['et_total_ht'] = $data['et_ht'] * $data['quantity'];
    $data['et_total_tva'] = $data['et_total_ht'] * Tva::getRate($data['tva_code'])/100;
    $event->data = $data;
  }

}