<?php

/**
 * ExtranetusersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtranetusersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtranetusersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Extranetusers');
    }
}