<?php

/**
 * FacetLine
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FacetLine extends BaseFacetLine
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('Facet as facet', array(
        'local' => 'facet_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('AttributeUnit as attribute_unit', array(
        'local' => 'attribute_unit_id',
        'foreign' => 'id'
      )
    );
  }

  public function preSave($event) {
    if ($this->type == self::TYPE_VALUE) {
      $this->ref_value = Utils::toDashAz09($this->value);
    } elseif($this->type == self::TYPE_INTERVAL) {
      $this->ref_value = Utils::toDashAz09($this->start.' a '.$this->end);
    }
  }

  const TYPE_VALUE = 0;
  const TYPE_INTERVAL = 1;
  public static $typeList = array(
    self::TYPE_VALUE => "valeur",
    self::TYPE_INTERVAL => "interval",
  );
  public static function getTypeText($const) {
    return isset(self::$typeList[$const]) ? self::$typeList[$const] : "";
  }

}
