<?php

/**
 * FacetLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacetLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacetLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FacetLine');
    }
}