<?php

/**
 * Facet
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Facet extends BaseFacet
{
  public function setUp() {
    parent::setUp();
    $this->hasMany('FacetLine as lines', array(
        'local' => 'id',
        'foreign' => 'facet_id'
      )
    );
    $this->hasOne('Families as family', array(
        'local' => 'family_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Attribute as attribute', array(
        'local' => 'attribute_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('AttributeUnit as attribute_unit', array(
        'local' => 'attribute_unit_id',
        'foreign' => 'id'
      )
    );
  }

  public function preSave($event) {
    $this->ref_title = Utils::toDashAz09($this->title);
  }

  const SHOW_UNIT_NONE = 0;
  const SHOW_UNIT_TITLE = 1;
  const SHOW_UNIT_VALUES = 2;
  const SHOW_UNIT_BOTH = 3;
  public static $showUnitList = array(
    self::SHOW_UNIT_NONE => "-",
    self::SHOW_UNIT_TITLE => "titre",
    self::SHOW_UNIT_VALUES => "valeurs",
    self::SHOW_UNIT_BOTH => "titre et valeurs",
  );
  public static function getShowUnitText($const) {
    return isset(self::$showUnitList[$const]) ? self::$showUnitList[$const] : "";
  }

  const TYPE_ALL = 0;
  const TYPE_PRODUCTS_ONLY = 1;
  // const TYPE_REFERENCES_ONLY = 2;
  public static $typeList = array(
    self::TYPE_ALL => "Facette Ref TC",
    self::TYPE_PRODUCTS_ONLY => "Facette virtuelle",
    // self::TYPE_REFERENCES_ONLY => "",
  );
  public static function getTypeText($const) {
    return isset(self::$typeList[$const]) ? self::$typeList[$const] : "";
  }

}
