<?php

/**
 * FamiliesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FamiliesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FamiliesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Families');
    }
}