<?php

/**
 * FamiliesFr
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FamiliesFr extends BaseFamiliesFr
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('Families as family', array(
        'local' => 'id',
        'foreign' => 'id'
      )
    );
  }

  public $maxId = 9999;

}
