<?php

/**
 * FamiliesFrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FamiliesFrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FamiliesFrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FamiliesFr');
    }
}