<?php

/**
 * InternalNotesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InternalNotesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InternalNotesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InternalNotes');
    }
}