<?php

/**
 * InvoiceLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvoiceLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvoiceLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvoiceLine');
    }
}