<?php

/**
 * MessengerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessengerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MessengerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Messenger');
    }
}