<?php

/**
 * MessengerPjsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessengerPjsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MessengerPjsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MessengerPjs');
    }
}