<?php

/**
 * MessengerPjs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MessengerPjs extends BaseMessengerPjs
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('UploadedFiles as file', array(
        'local' => 'id_uploaded_files',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Messenger as message', array(
        'local' => 'id_messenger',
        'foreign' => 'id'
      )
    );
  }

}