<?php

/**
 * MiniStoresMarketingLinksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MiniStoresMarketingLinksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MiniStoresMarketingLinksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MiniStoresMarketingLinks');
    }
}