<?php

/**
 * MiniStoresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MiniStoresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MiniStoresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MiniStores');
    }
}