<?php

/**
 * OrderLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderLine');
    }
}