<?php

/**
 * PaniersProduitsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaniersProduitsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaniersProduitsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaniersProduits');
    }
}