<?php

/**
 * Paniers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Paniers extends BasePaniers
{
  public function setUp() {
    parent::setUp();
    $this->hasMany('PaniersProduits as lines', array(
        'local' => 'id',
        'foreign' => 'idPanier',
        'cascade' => array('delete')
      )
    );
    $this->hasOne('Clients as client', array(
        'local' => 'idClient',
        'foreign' => 'id'
      )
    );
    $this->hasOne('ClientsAdresses as delivery_address', array(
        'local' => 'delivery_address_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('ClientsAdresses as billing_address', array(
        'local' => 'billing_address_id',
        'foreign' => 'id'
      )
    );
  }
  
  public function checkAndCorrectAddresses($abt = null) { // addresses by type for the currently set client
    if (!isset($abt))
      $abt = ClientsAdresses::orderByType($this->client->addresses->toArray());
    
    $type_d = ClientsAdresses::TYPE_DELIVERY;
    $type_b = ClientsAdresses::TYPE_BILLING;
    
    // something went wrong somewhere
    if (!$abt[$type_d]['length'])
      return false;
      
    // the set delivery address doesn't exist or doesn't belong to the client, use the default one
    if (!isset($this->delivery_address) || !isset($abt[$type_d]['list'][$this->delivery_address_id])) {
      $dda = reset($abt[$type_d]['list']);
      $this->delivery_address_id = $dda['id'];
    }
    
    if ($abt[$type_b]['length']) {
      // the billing address doesn't belong to the client set ones -> get the default one
      if (!isset($this->billing_address) || !isset($abt[$type_b]['list'][$this->billing_address_id])) {
        $dba = reset($abt[$type_b]['list']);
        $this->billing_address_id = $dba['id'];
      }
    } else {
      // there is no billing address set for the client, but the billing isn't set to the delivery one -> correct it
      if ($this->billing_address_id != $this->delivery_address_id) {
        $dba = $this->delivery_address;
        $this->billing_address_id = $this->delivery_address_id;
      }
    }
    
    return true;
  }
}