<?php

/**
 * PaniersProduits
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PaniersProduits extends BasePaniersProduits
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('Paniers as cart', array(
        'local' => 'idPanier',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Products as product', array(
        'local' => 'idProduct',
        'foreign' => 'id'
      )
    );
    $this->hasOne('ReferencesContent as pdt_ref', array(
        'local' => 'idTC',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Families as category', array(
        'local' => 'idFamily',
        'foreign' => 'id'
      )
    );
  }

}