<?php

/**
 * PaniersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaniersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaniersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Paniers');
    }
}