<?php

/**
 * ProductsLinked
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductsLinked extends BaseProductsLinked
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('Products as product_linked_to', array(
        'local' => 'pdt_id',
        'foreign' => 'id'
      )
    );
    $this->hasMany('Products as products_linked', array(
        'local' => 'pdt_linked_id',
        'foreign' => 'id'
      )
    );
  }

}