<?php

/**
 * ProductsStats
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductsStats extends BaseProductsStats
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('Products as product', array(
        'local' => 'id',
        'foreign' => 'id'
      )
    );
  }
}