<?php

/**
 * ProductsNotationsSpoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsNotationsSpoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsNotationsSpoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductsNotationsSpool');
    }
}