<?php

/**
 * ProductsNotationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsNotationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsNotationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductsNotations');
    }
}