<?php

/**
 * ProductAttribute
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductAttribute extends BaseProductAttribute
{
  public function setUp() {
    parent::setUp();
    $this->hasMany('ProductReferenceAttribute as product_reference_attributes', array(
        'local' => 'id',
        'foreign' => 'product_attribute_id'
      )
    );
    $this->hasOne('Products as product', array(
        'local' => 'product_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Attribute as attribute', array(
        'local' => 'attribute_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('AttributeUnit as attribute_unit', array(
        'local' => 'attribute_unit_id',
        'foreign' => 'id'
      )
    );
  }

}
