<?php

/**
 * ProductsFrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsFrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsFrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductsFr');
    }
}