<?php

/**
 * ProductsNotations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductsNotations extends BaseProductsNotations
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('Products as product', array(
        'local' => 'id_product',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Clients as client', array(
        'local' => 'id_client',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Order as order', array(
        'local' => 'id_commande',
        'foreign' => 'id'
      )
    );
  }

}