<?php

/**
 * ProductReferenceAttribute
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductReferenceAttribute extends BaseProductReferenceAttribute
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('ProductAttribute as product_attribute', array(
        'local' => 'product_attribute_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('ReferencesContent as product_reference', array(
        'local' => 'product_reference_id',
        'foreign' => 'id'
      )
    );
  }

}
