<?php

/**
 * ProductsRelatedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsRelatedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsRelatedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductsRelated');
    }
}