<?php

/**
 * ProductsStatsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsStatsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsStatsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductsStats');
    }
}