<?php

/**
 * ProductsSavedListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsSavedListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsSavedListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductsSavedList');
    }
}