<?php

/**
 * ProductsLinkedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsLinkedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsLinkedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductsLinked');
    }
}