<?php

/**
 * ProductsFamiliesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsFamiliesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsFamiliesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductsFamilies');
    }
}