<?php

/**
 * RefAttributesVirtualProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefAttributesVirtualProductsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefAttributesVirtualProductsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefAttributesVirtualProducts');
    }
}