<?php

/**
 * RefAttributesIntervalsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefAttributesIntervalsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefAttributesIntervalsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefAttributesIntervals');
    }
}