<?php

/**
 * RefAttributesValuesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefAttributesValuesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefAttributesValuesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefAttributesValues');
    }
}