<?php

/**
 * RefAttributesVirtual
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RefAttributesVirtual extends BaseRefAttributesVirtual
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('RefAttributes as ref_attribute', array(
        'local' => 'attributeId',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Families as family', array(
        'local' => 'categoryId',
        'foreign' => 'id'
      )
    );
    $this->hasMany('RefAttributesVirtualProducts as linked_products', array(
        'local' => 'id',
        'foreign' => 'id_ref_attribute_virtual'
      )
    );
  }
}
