<?php

/**
 * RefAttributesVirtualTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefAttributesVirtualTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefAttributesVirtualTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefAttributesVirtual');
    }
}