<?php

/**
 * RefAttributesVirtualProducts
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RefAttributesVirtualProducts extends BaseRefAttributesVirtualProducts
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('RefAttributesVirtual as virtual_attribute_line', array(
        'local' => 'id_ref_attribute_virtual',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Products as product', array(
        'local' => 'id_product',
        'foreign' => 'id'
      )
    );
  }
}
