<?php

/**
 * RefAttributesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefAttributesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefAttributesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefAttributes');
    }
}