<?php

/**
 * ReferencesCols
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ReferencesCols extends BaseReferencesCols
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('Products as product', array(
        'local' => 'idProduct',
        'foreign' => 'id'
      )
    );
    $this->hasMany('ReferencesContent as contents', array(
        'local' => 'idProduct',
        'foreign' => 'idProduct'
      )
    );
  }

  public function construct() {
    $this->mapValue('c_headers', array());
  }

  public function postHydrate($event) {
    $data = $event->data;
    $data['c_headers'] = !empty($data['content']) ? array_slice(mb_unserialize($data['content']), 3, -6) : array();
    $event->data = $data;
  }

}
