<?php

/**
 * ReferencesContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReferencesContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReferencesContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReferencesContent');
    }
}