<?php

/**
 * ReferencesContent
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ReferencesContent extends BaseReferencesContent
{
  public function setUp() {
    parent::setUp();
    $this->hasOne('Products as product', array(
        'local' => 'idProduct',
        'foreign' => 'id'
      )
    );
    $this->hasOne('Advertisers as supplier', array(
        'local' => 'sup_id',
        'foreign' => 'id'
      )
    );
    $this->hasOne('ReferencesCols as headers', array(
        'local' => 'idProduct',
        'foreign' => 'idProduct'
      )
    );
    $this->hasMany('EstimateLine as estimates_lines', array(
        'local' => 'id',
        'foreign' => 'pdt_ref_id'
      )
    );
    $this->hasMany('OrderLine as orders_lines', array(
        'local' => 'id',
        'foreign' => 'pdt_ref_id'
      )
    );
    $this->hasMany('InvoiceLine as invoices_lines', array(
        'local' => 'id',
        'foreign' => 'pdt_ref_id'
      )
    );
    $this->hasMany('ProductReferenceAttribute as attribute_values', array(
        'local' => 'id',
        'foreign' => 'product_reference_id'
      )
    );
  }

  public function construct() {
    $this->mapValue('c_cols', array());
  }

  public function postHydrate($event) {
    $data = $event->data;
    $data['c_cols'] = !empty($data['content']) ? mb_unserialize($data['content'])  : array();
    $event->data = $data;
  }

}
