<?php

/**
 * ReferencesColsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReferencesColsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReferencesColsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReferencesCols');
    }
}