<?php

/**
 * SupplierOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SupplierOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SupplierOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SupplierOrder');
    }
}