<?php

/**
 * TvaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tva');
    }
}