<?php

/**
 * UploadedFilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UploadedFilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UploadedFilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UploadedFiles');
    }
}